### ISSUE TITLE
Error al ejecutar workflow

### ISSUE THREAD

**Issue by beltranprieto** [beltranprieto/practica-github-actions#1]
Tengo el siguiente código

```
name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Node.js
        run: |
        node -v
```

Me aparece error de sintaxis pero no lo puedo identificar, ¿me puedes ayudar?

Gracias
